//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySql.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MySql.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Improper MySqlCommandBuilder state: adapter is null 的本地化字符串。
        /// </summary>
        public static string AdapterIsNull {
            get {
                return ResourceManager.GetString("AdapterIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Improper MySqlCommandBuilder state: adapter&apos;s SelectCommand is null 的本地化字符串。
        /// </summary>
        public static string AdapterSelectIsNull {
            get {
                return ResourceManager.GetString("AdapterSelectIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version string not in acceptable format 的本地化字符串。
        /// </summary>
        public static string BadVersionFormat {
            get {
                return ResourceManager.GetString("BadVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  The buffer cannot be null 的本地化字符串。
        /// </summary>
        public static string BufferCannotBeNull {
            get {
                return ResourceManager.GetString("BufferCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Buffer is not large enough 的本地化字符串。
        /// </summary>
        public static string BufferNotLargeEnough {
            get {
                return ResourceManager.GetString("BufferNotLargeEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Canceling an executing query requires MySQL 5.0 or higher. 的本地化字符串。
        /// </summary>
        public static string CancelNeeds50 {
            get {
                return ResourceManager.GetString("CancelNeeds50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Canceling an active query is only supported on MySQL 5.0.0 and above.  的本地化字符串。
        /// </summary>
        public static string CancelNotSupported {
            get {
                return ResourceManager.GetString("CancelNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MySqlCommandBuilder does not support multi-table statements 的本地化字符串。
        /// </summary>
        public static string CBMultiTableNotSupported {
            get {
                return ResourceManager.GetString("CBMultiTableNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MySqlCommandBuilder cannot operate on tables with no unique or key columns 的本地化字符串。
        /// </summary>
        public static string CBNoKeyColumn {
            get {
                return ResourceManager.GetString("CBNoKeyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chaos isolation level is not supported 的本地化字符串。
        /// </summary>
        public static string ChaosNotSupported {
            get {
                return ResourceManager.GetString("ChaosNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The CommandText property has not been properly initialized. 的本地化字符串。
        /// </summary>
        public static string CommandTextNotInitialized {
            get {
                return ResourceManager.GetString("CommandTextNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The connection is already open. 的本地化字符串。
        /// </summary>
        public static string ConnectionAlreadyOpen {
            get {
                return ResourceManager.GetString("ConnectionAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection unexpectedly terminated. 的本地化字符串。
        /// </summary>
        public static string ConnectionBroken {
            get {
                return ResourceManager.GetString("ConnectionBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection must be valid and open 的本地化字符串。
        /// </summary>
        public static string ConnectionMustBeOpen {
            get {
                return ResourceManager.GetString("ConnectionMustBeOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The connection is not open. 的本地化字符串。
        /// </summary>
        public static string ConnectionNotOpen {
            get {
                return ResourceManager.GetString("ConnectionNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The connection property has not been set or is null. 的本地化字符串。
        /// </summary>
        public static string ConnectionNotSet {
            get {
                return ResourceManager.GetString("ConnectionNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Count cannot be negative 的本地化字符串。
        /// </summary>
        public static string CountCannotBeNegative {
            get {
                return ResourceManager.GetString("CountCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SetLength is not a valid operation on CompressedStream 的本地化字符串。
        /// </summary>
        public static string CSNoSetLength {
            get {
                return ResourceManager.GetString("CSNoSetLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is already an open DataReader associated with this Connection which must be closed first. 的本地化字符串。
        /// </summary>
        public static string DataReaderOpen {
            get {
                return ResourceManager.GetString("DataReaderOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The default connection encoding was not found. Please report this as a bug along with your connection string and system details. 的本地化字符串。
        /// </summary>
        public static string DefaultEncodingNotFound {
            get {
                return ResourceManager.GetString("DefaultEncodingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MySQL Connector/Net does not currently support distributed transactions. 的本地化字符串。
        /// </summary>
        public static string DistributedTxnNotSupported {
            get {
                return ResourceManager.GetString("DistributedTxnNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error creating socket connection 的本地化字符串。
        /// </summary>
        public static string ErrorCreatingSocket {
            get {
                return ResourceManager.GetString("ErrorCreatingSocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fatal error encountered during command execution. 的本地化字符串。
        /// </summary>
        public static string FatalErrorDuringExecute {
            get {
                return ResourceManager.GetString("FatalErrorDuringExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fatal error encountered during data read. 的本地化字符串。
        /// </summary>
        public static string FatalErrorDuringRead {
            get {
                return ResourceManager.GetString("FatalErrorDuringRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fatal error encountered attempting to read the resultset. 的本地化字符串。
        /// </summary>
        public static string FatalErrorReadingResult {
            get {
                return ResourceManager.GetString("FatalErrorReadingResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 From index and length use more bytes than from contains 的本地化字符串。
        /// </summary>
        public static string FromAndLengthTooBig {
            get {
                return ResourceManager.GetString("FromAndLengthTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 From index must be a valid index inside the from buffer 的本地化字符串。
        /// </summary>
        public static string FromIndexMustBeValid {
            get {
                return ResourceManager.GetString("FromIndexMustBeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Call to GetHostEntry failed after {0} while querying for hostname &apos;{1}&apos;: SocketErrorCode={2}, ErrorCode={3}, NativeErrorCode={4}. 的本地化字符串。
        /// </summary>
        public static string GetHostEntryFailed {
            get {
                return ResourceManager.GetString("GetHostEntryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retrieving procedure metadata for {0} from server. 的本地化字符串。
        /// </summary>
        public static string HardProcQuery {
            get {
                return ResourceManager.GetString("HardProcQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value has an unsupported format. 的本地化字符串。
        /// </summary>
        public static string ImproperValueFormat {
            get {
                return ResourceManager.GetString("ImproperValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An incorrect response was received from the server. 的本地化字符串。
        /// </summary>
        public static string IncorrectTransmission {
            get {
                return ResourceManager.GetString("IncorrectTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index and length use more bytes than to has room for 的本地化字符串。
        /// </summary>
        public static string IndexAndLengthTooBig {
            get {
                return ResourceManager.GetString("IndexAndLengthTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index must be a valid position in the buffer 的本地化字符串。
        /// </summary>
        public static string IndexMustBeValid {
            get {
                return ResourceManager.GetString("IndexMustBeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Procedure or function &apos;{0}&apos; cannot be found in database &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        public static string InvalidProcName {
            get {
                return ResourceManager.GetString("InvalidProcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keyword does not allow null values. 的本地化字符串。
        /// </summary>
        public static string KeywordNoNull {
            get {
                return ResourceManager.GetString("KeywordNoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keyword not supported. 的本地化字符串。
        /// </summary>
        public static string KeywordNotSupported {
            get {
                return ResourceManager.GetString("KeywordNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When MySqlCommandBuilder.ReturnGeneratedIdentifiers is true, MySqlCommand.UpdatedRowSource must be set to None. 的本地化字符串。
        /// </summary>
        public static string MixingUpdatedRowSource {
            get {
                return ResourceManager.GetString("MixingUpdatedRowSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple simultaneous connections or connections with different connection strings inside the same transaction are not currently supported. 的本地化字符串。
        /// </summary>
        public static string MultipleConnectionsInTransactionNotSupported {
            get {
                return ResourceManager.GetString("MultipleConnectionsInTransactionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NamedPipeStream does not support seeking 的本地化字符串。
        /// </summary>
        public static string NamedPipeNoSeek {
            get {
                return ResourceManager.GetString("NamedPipeNoSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NamedPipeStream doesn&apos;t support SetLength 的本地化字符串。
        /// </summary>
        public static string NamedPipeNoSetLength {
            get {
                return ResourceManager.GetString("NamedPipeNoSetLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid attempt to call NextResult when the reader is closed. 的本地化字符串。
        /// </summary>
        public static string NextResultIsClosed {
            get {
                return ResourceManager.GetString("NextResultIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When calling stored procedures and &apos;Use Procedure Bodies&apos; is false, all parameters must have their type explicitly set. 的本地化字符串。
        /// </summary>
        public static string NoBodiesAndTypeNotSet {
            get {
                return ResourceManager.GetString("NoBodiesAndTypeNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nested transactions are not supported. 的本地化字符串。
        /// </summary>
        public static string NoNestedTransactions {
            get {
                return ResourceManager.GetString("NoNestedTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The object is not open or has been disposed. 的本地化字符串。
        /// </summary>
        public static string ObjectDisposed {
            get {
                return ResourceManager.GetString("ObjectDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Offset cannot be negative 的本地化字符串。
        /// </summary>
        public static string OffsetCannotBeNegative {
            get {
                return ResourceManager.GetString("OffsetCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offset must be a valid position in buffer 的本地化字符串。
        /// </summary>
        public static string OffsetMustBeValid {
            get {
                return ResourceManager.GetString("OffsetMustBeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter &apos;{0}&apos; has already been defined. 的本地化字符串。
        /// </summary>
        public static string ParameterAlreadyDefined {
            get {
                return ResourceManager.GetString("ParameterAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter cannot have a negative value 的本地化字符串。
        /// </summary>
        public static string ParameterCannotBeNegative {
            get {
                return ResourceManager.GetString("ParameterCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter cannot be null 的本地化字符串。
        /// </summary>
        public static string ParameterCannotBeNull {
            get {
                return ResourceManager.GetString("ParameterCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter is invalid. 的本地化字符串。
        /// </summary>
        public static string ParameterIsInvalid {
            get {
                return ResourceManager.GetString("ParameterIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter &apos;{0}&apos; must be defined. 的本地化字符串。
        /// </summary>
        public static string ParameterMustBeDefined {
            get {
                return ResourceManager.GetString("ParameterMustBeDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password must be valid and contain length characters 的本地化字符串。
        /// </summary>
        public static string PasswordMustHaveLegalChars {
            get {
                return ResourceManager.GetString("PasswordMustHaveLegalChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This category includes a series of counters for MySQL. 的本地化字符串。
        /// </summary>
        public static string PerfMonCategoryHelp {
            get {
                return ResourceManager.GetString("PerfMonCategoryHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .NET Data Provider for MySQL 的本地化字符串。
        /// </summary>
        public static string PerfMonCategoryName {
            get {
                return ResourceManager.GetString("PerfMonCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The number of times a procedures metadata had to be queried from the server. 的本地化字符串。
        /// </summary>
        public static string PerfMonHardProcHelp {
            get {
                return ResourceManager.GetString("PerfMonHardProcHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hard Procedure Queries 的本地化字符串。
        /// </summary>
        public static string PerfMonHardProcName {
            get {
                return ResourceManager.GetString("PerfMonHardProcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The number of times a procedures metadata was retrieved from the client-side cache. 的本地化字符串。
        /// </summary>
        public static string PerfMonSoftProcHelp {
            get {
                return ResourceManager.GetString("PerfMonSoftProcHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Soft Procedure Queries 的本地化字符串。
        /// </summary>
        public static string PerfMonSoftProcName {
            get {
                return ResourceManager.GetString("PerfMonSoftProcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 same name are not supported. 的本地化字符串。
        /// </summary>
        public static string ProcAndFuncSameName {
            get {
                return ResourceManager.GetString("ProcAndFuncSameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Packets larger than max_allowed_packet are not allowed. 的本地化字符串。
        /// </summary>
        public static string QueryTooLarge {
            get {
                return ResourceManager.GetString("QueryTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reading from the stream has failed. 的本地化字符串。
        /// </summary>
        public static string ReadFromStreamFailed {
            get {
                return ResourceManager.GetString("ReadFromStreamFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Routine &apos;{0}&apos; cannot be found. Either check the spelling or make sure you have sufficient rights to execute the routine. 的本地化字符串。
        /// </summary>
        public static string RoutineNotFound {
            get {
                return ResourceManager.GetString("RoutineNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Socket streams do not support seeking 的本地化字符串。
        /// </summary>
        public static string SocketNoSeek {
            get {
                return ResourceManager.GetString("SocketNoSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retrieving procedure metadata for {0} from procedure cache. 的本地化字符串。
        /// </summary>
        public static string SoftProcQuery {
            get {
                return ResourceManager.GetString("SoftProcQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stored procedures are not supported on this version of MySQL 的本地化字符串。
        /// </summary>
        public static string SPNotSupported {
            get {
                return ResourceManager.GetString("SPNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The stream has already been closed 的本地化字符串。
        /// </summary>
        public static string StreamAlreadyClosed {
            get {
                return ResourceManager.GetString("StreamAlreadyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  The stream does not support reading 的本地化字符串。
        /// </summary>
        public static string StreamNoRead {
            get {
                return ResourceManager.GetString("StreamNoRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The stream does not support writing 的本地化字符串。
        /// </summary>
        public static string StreamNoWrite {
            get {
                return ResourceManager.GetString("StreamNoWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. 的本地化字符串。
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout expired but command object was null.  This should not happen. 的本地化字符串。
        /// </summary>
        public static string TimeoutExpiredNullObject {
            get {
                return ResourceManager.GetString("TimeoutExpiredNullObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error connecting: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached. 的本地化字符串。
        /// </summary>
        public static string TimeoutGettingConnection {
            get {
                return ResourceManager.GetString("TimeoutGettingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to connect to any of the specified MySQL hosts. 的本地化字符串。
        /// </summary>
        public static string UnableToConnectToHost {
            get {
                return ResourceManager.GetString("UnableToConnectToHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to execute stored procedure &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        public static string UnableToExecuteSP {
            get {
                return ResourceManager.GetString("UnableToExecuteSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an error parsing the foreign key definition. 的本地化字符串。
        /// </summary>
        public static string UnableToParseFK {
            get {
                return ResourceManager.GetString("UnableToParseFK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to retrieve stored routine parameters.  Either grant access to the routine or add the &apos;Use Procedure Bodies=false&apos; option to your connection string. 的本地化字符串。
        /// </summary>
        public static string UnableToRetrieveParameters {
            get {
                return ResourceManager.GetString("UnableToRetrieveParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to retrieve stored procedure metadata for routine &apos;{0}&apos;.  Either grant  SELECT privilege to mysql.proc for this user or use &quot;use procedure bodies=false&quot; with  your connection string. 的本地化字符串。
        /// </summary>
        public static string UnableToRetrieveSProcData {
            get {
                return ResourceManager.GetString("UnableToRetrieveSProcData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unix sockets are not supported on Windows 的本地化字符串。
        /// </summary>
        public static string UnixSocketsNotSupported {
            get {
                return ResourceManager.GetString("UnixSocketsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The requested column value could not be treated as or conveted to a Guid. 的本地化字符串。
        /// </summary>
        public static string ValueNotSupportedForGuid {
            get {
                return ResourceManager.GetString("ValueNotSupportedForGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Writing to the stream failed. 的本地化字符串。
        /// </summary>
        public static string WriteToStreamFailed {
            get {
                return ResourceManager.GetString("WriteToStreamFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter &apos;{0}&apos; is not found but a parameter with the name &apos;{1}&apos; is found. Parameter names must include the leading parameter marker. 的本地化字符串。
        /// </summary>
        public static string WrongParameterName {
            get {
                return ResourceManager.GetString("WrongParameterName", resourceCulture);
            }
        }
    }
}
